version: '3.9'
services:
  database:
      image: postgres:15
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Chapeco2022
        - POSTGRES_DB=planejamento
      ports:
        - 5432:5432
      volumes:
        - database-data:/var/lib/postgresql/data
volumes:
  database-data: